export const BirdData = [
    {
        name: 'European Robin',
        scienceName: 'Erithacus rubecula',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Erithacus_rubecula_with_cocked_head.jpg/440px-Erithacus_rubecula_with_cocked_head.jpg',
        miniSummary: 'The European robin is a small and friendly bird with a red breast and a sweet, melodious song.',
        bigSummary: 'The European robin (Erithacus rubecula) is a common garden bird in the UK. Known for its red breast and inquisitive nature, robins are often seen near humans. They have a diet that includes insects, worms, and berries. In folklore, robins are associated with Christmas and are considered symbols of good luck.',
        seen: 3000,
    },
    {
        name: 'Blue Tit',
        scienceName: 'Cyanistes caeruleus',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Eurasian_blue_tit_Lancashire.jpg/440px-Eurasian_blue_tit_Lancashire.jpg',
        miniSummary: 'The blue tit is a small and colorful bird known for its blue and yellow plumage and energetic behavior.',
        bigSummary: 'The blue tit (Cyanistes caeruleus) is a common garden bird in the UK. It has bright blue and yellow plumage with a distinctive white face. Blue tits are active and acrobatic, often seen hanging upside down to feed. They have a varied diet that includes insects, seeds, and suet.',
        seen: 3000,
    },
    {
        name: 'Blackbird',
        scienceName: 'Turdus merula',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Common_Blackbird.jpg/440px-Common_Blackbird.jpg',
        miniSummary: 'The blackbird is a common thrush species known for its black plumage and beautiful song.',
        bigSummary: 'The blackbird (Turdus merula) is a familiar sight in gardens and woodlands across the UK. Male blackbirds have black plumage, while females are brown. They are known for their melodious song, and each individual may have a unique repertoire. Blackbirds feed on a variety of foods, including insects, worms, and fruits.',
        seen: 2500,
    },
    {
        name: 'Goldfinch',
        scienceName: 'Carduelis carduelis',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Carduelis_carduelis_close_up.jpg/440px-Carduelis_carduelis_close_up.jpg',
        miniSummary: 'The goldfinch is a small, brightly colored bird with distinctive red, black, and yellow markings.',
        bigSummary: 'The goldfinch (Carduelis carduelis) is a vibrant bird with red, black, and yellow plumage. They are often seen in gardens and open countryside. Goldfinches have a specialized diet, primarily feeding on seeds, especially those of thistles. They are social birds and often form flocks.',
        seen: 1800,
    },
    {
        name: 'Peregrine Falcon',
        scienceName: 'Falco peregrinus',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg/440px-Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg',
        miniSummary: 'The peregrine falcon is a powerful bird of prey known for its incredible speed, agility, and hunting stoops.',
        bigSummary: 'The peregrine falcon (Falco peregrinus) is among the fastest animals on Earth, reaching speeds over 240 miles per hour during high-speed dives. Found in various habitats, including cliffs and cities, peregrine falcons primarily feed on other birds captured mid-air.',
        seen: 1200,
    },
    {
        name: 'Common Kestrel',
        scienceName: 'Falco tinnunculus',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Common_kestrel_falco_tinnunculus.jpg/440px-Common_kestrel_falco_tinnunculus.jpg',
        miniSummary: 'The common kestrel is a small falcon known for its hovering hunting technique and distinctive plumage.',
        bigSummary: 'The common kestrel (Falco tinnunculus) is a familiar sight in the UK, often seen hovering in the sky while hunting for prey. They have a varied diet that includes small mammals, birds, and insects. Kestrels are adaptable birds, found in a range of habitats from urban areas to open countryside.',
        seen: 800,
    },
    {
        name: 'Wood Pigeon',
        scienceName: 'Columba palumbus',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Columba_palumbus_-garden_post-8.jpg/440px-Columba_palumbus_-garden_post-8.jpg',
        miniSummary: 'The wood pigeon is a large and common pigeon species found in parks, gardens, and wooded areas.',
        bigSummary: 'The wood pigeon (Columba palumbus) is one of the largest pigeon species in the UK. They have a distinctive cooing call and are often seen perched in trees or foraging on the ground for seeds and grains. Wood pigeons are adaptable and can be found in a variety of habitats.',
        seen: 1500,
    },
    {
        name: 'Great Tit',
        scienceName: 'Parus major',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Great_tit_side-on.jpg/440px-Great_tit_side-on.jpg',
        miniSummary: 'The great tit is a common and colorful tit species known for its black head, white cheeks, and yellow breast.',
        bigSummary: 'The great tit (Parus major) is a familiar garden bird in the UK. It has a varied diet that includes insects, seeds, and berries. Great tits are known for their acrobatic feeding behavior and can be found in a wide range of habitats, from woodlands to urban gardens.',
        seen: 2000,
    },
    {
        name: 'Sparrow',
        scienceName: 'Passeridae',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/House_sparrow_male_in_Prospect_Park_%2853532%29.jpg/440px-House_sparrow_male_in_Prospect_Park_%2853532%29.jpg',
        miniSummary: 'The house sparrow is a small bird with a brown and gray plumage, often found in urban areas and gardens.',
        bigSummary: 'The house sparrow (Passer domesticus) is a familiar bird in the UK, known for its close association with human habitats. Male sparrows have distinctive black bibs on their throats. They feed on a varied diet that includes seeds, insects, and crumbs. Sparrows are social birds and often form flocks.',
        seen: 1800,
    },
    {
        name: 'Long-tailed Tit',
        scienceName: 'Aegithalos caudatus',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Aegithalos_caudatus_side-on.jpg/440px-Aegithalos_caudatus_side-on.jpg',
        miniSummary: 'The long-tailed tit is a small and fluffy bird with distinctive black and white plumage and a long tail.',
        bigSummary: 'The long-tailed tit (Aegithalos caudatus) is a charming bird often seen in woodlands and gardens. They travel in family groups, chattering and flitting from branch to branch. Long-tailed tits feed on insects and spiders, and their nests are unique, resembling a hanging sock made of moss and feathers.',
        seen: 1200,
    },
    {
        name: 'Collared Dove',
        scienceName: 'Streptopelia decaocto',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Eurasian_collared-dove_%28Streptopelia_decaocto%29.jpg/440px-Eurasian_collared-dove_%28Streptopelia_decaocto%29.jpg',
        miniSummary: 'The collared dove is a medium-sized dove with a pale gray body, a distinctive black collar, and red eyes.',
        bigSummary: 'The collared dove (Streptopelia decaocto) is a common sight in gardens and urban areas. They have a soft, cooing call and feed on seeds and grains. Collared doves are adaptable and can be found in a variety of environments. They are often seen perched on wires or foraging on the ground.',
        seen: 2500,
    },
    {
        name: 'Magpie',
        scienceName: 'Pica pica',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg/440px-Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg',
        miniSummary: 'The magpie is a black and white bird known for its long tail and sometimes mischievous behavior.',
        bigSummary: 'The magpie (Pica pica) is a highly intelligent and adaptable bird in the crow family. They have a striking black and white plumage, and their long tail is a distinctive feature. Magpies are omnivores, feeding on a wide range of food, including insects, small mammals, and scraps. They are known for their vocalizations and are often associated with superstitions.',
        seen: 2000,
    },
    {
        name: 'Chaffinch',
        scienceName: 'Fringilla coelebs',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Chaffinch_%28Fringilla_coelebs%29.jpg/440px-Chaffinch_%28Fringilla_coelebs%29.jpg',
        miniSummary: 'The chaffinch is a colorful finch with a pinkish-red breast and blue-gray crown, often seen in woodlands.',
        bigSummary: 'The chaffinch (Fringilla coelebs) is a common and colorful finch in the UK. Male chaffinches have a pinkish-red breast and a blue-gray cap, while females have more subdued colors. They feed on seeds and insects and are known for their vibrant song. Chaffinches are social birds and often gather in flocks.',
        seen: 1500,
    },
    {
        name: 'Wren',
        scienceName: 'Troglodytes troglodytes',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Cistothorus_palustris_Iona.jpg/440px-Cistothorus_palustris_Iona.jpg',
        miniSummary: 'The wren is a small bird with a brown plumage, often found in woodlands and dense vegetation.',
        bigSummary: 'The wren (Troglodytes troglodytes) is one of the smallest birds in the UK. Despite its size, it has a powerful and melodious song. Wrens are highly active, foraging for insects and spiders in dense vegetation. They build dome-shaped nests hidden in shrubs and low branches.',
        seen: 800,
    },
    {
        name: 'Nuthatch',
        scienceName: 'Sitta europaea',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Sitta_europaea_-Rouge_Cloitre_estate%2C_Sonian_Forest%2C_near_Brussels%2C_Belgium-8.jpg/440px-Sitta_europaea_-Rouge_Cloitre_estate%2C_Sonian_Forest%2C_near_Brussels%2C_Belgium-8.jpg',
        miniSummary: 'The nuthatch is a small bird with blue-gray plumage, a black eyestripe, and a habit of climbing down tree trunks headfirst.',
        bigSummary: 'The nuthatch (Sitta europaea) is an acrobatic bird often seen in woodlands and parks. It has a unique ability to climb down trees headfirst, thanks to its strong toes. Nuthatches feed on insects, seeds, and nuts. They are known for their loud calls and territorial behavior.',
        seen: 1200,
    },
];
