// All summaries are from the RSPB https://www.rspb.org.uk.
export const BirdData = [
    {
        name: 'Blue Tit',
        scienceName: 'Cyanistes caeruleus',
        alt:'Blue Tit perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Eurasian_blue_tit_Lancashire.jpg/440px-Eurasian_blue_tit_Lancashire.jpg',
        miniSummary: 'A colourful mix of blue, yellow, white and green makes the Blue Tit.',
        bigSummary: 'A colourful mix of blue, yellow, white and green makes the Blue Tit one of our most attractive and most recognisable garden visitors. In winter, family flocks join up with other tits as they search for food. A garden with four or five Blue Tits at a feeder at any one time may be feeding 20 or more.',
        seen: 3000,
    },
    {
        name: 'Blackbird',
        scienceName: 'Turdus merula',
        alt:'Blackbird perched on the grass looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Common_Blackbird.jpg/440px-Common_Blackbird.jpg',
        miniSummary: 'Male Blackbirds are black with a bright orange-yellow beak and yellow eye-ring...',
        bigSummary: 'Male Blackbirds are black with a bright orange-yellow beak and yellow eye-ring. Females are brown often with spots and streaks on their breasts and brown beak. The Blackbird is one of the most common UK birds and one of the most striking. Its mellow song is also a favourite. ',
        seen: 2500,
    },
    {
        name: 'Goldfinch',
        scienceName: 'Carduelis carduelis',
        alt:'Goldfinch perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Carduelis_carduelis_close_up.jpg/440px-Carduelis_carduelis_close_up.jpg',
        miniSummary: 'The Goldfinch is a colourful finch with a bright red face and yellow wing patch.',
        bigSummary: 'The Goldfinch is a colourful finch with a bright red face and yellow wing patch. It\'s a very sociable bird, often breeding in loose groups. It has a delightful twittering song and call. Their fine beaks allow them to extract otherwise inaccessible seeds from thistles and teasels. Increasingly, they are visiting bird tables and feeders. In winter, many UK Goldfinches migrate as far south as Spain.',
        seen: 1800,
    },
    {
        name: 'Kestrel',
        scienceName: 'Falco tinnunculus',
        alt:'Common Kestrel perched on a branch looking behind to the camera',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Common_kestrel_falco_tinnunculus.jpg/440px-Common_kestrel_falco_tinnunculus.jpg',
        miniSummary: 'Kestrels are a familiar sight, with their pointed wings and long tail, hovering beside a roadside verge.',
        bigSummary: 'Kestrels are a familiar sight, with their pointed wings and long tail, hovering beside a roadside verge. Numbers of Kestrels have declined since the 1970s, probably as a result of changes in farming, and so it is included on the Amber List. They have adapted readily to man-made environments and can survive right in the centre of cities. ',
        seen: 800,
    },
    {
        name: 'Wood Pigeon',
        scienceName: 'Columba palumbus',
        alt:'Wood Pigeon perched on a branch looking to the right',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Columba_palumbus_-garden_post-8.jpg/440px-Columba_palumbus_-garden_post-8.jpg',
        miniSummary: 'The UK\'s largest and commonest pigeon, the Woodpigeon is largely grey with a white neck patch and white wing patches.',
        bigSummary: 'The UK\'s largest and commonest pigeon, the Woodpigeon is largely grey with a white neck patch and white wing patches, clearly visible in flight. Although shy in the countryside it can be tame and approachable in towns and cities. Its cooing call is a familiar sound in woodland as is the loud clatter of its wings when it flies away. ',
        seen: 1500,
    },
    {
        name: 'Great Tit',
        scienceName: 'Parus major',
        alt:'Great Tit perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Great_tit_side-on.jpg/440px-Great_tit_side-on.jpg',
        miniSummary: 'The great tit has a green and yellow body and a striking glossy black head with white cheeks.',
        bigSummary: 'The great tit has a green and yellow body and a striking glossy black head with white cheeks. It\'s a woodland bird that has readily adapted to man-made habitats to become a familiar garden visitor. It can be quite aggressive at a bird table, fighting off smaller tits. In winter, it joins with Blue Tits and others to form roaming flocks which scour gardens and countryside for food.',
        seen: 2000,
    },
    {
        name: 'Sparrow',
        scienceName: 'Passeridae',
        alt:'Sparrow perched on a branch looking to the right',

        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/House_sparrow_male_in_Prospect_Park_%2853532%29.jpg/440px-House_sparrow_male_in_Prospect_Park_%2853532%29.jpg',
        miniSummary: 'These noisy and sociable birds are found around the world, thanks to their cheerful ability',
        bigSummary: 'These noisy and sociable birds are found around the world, thanks to their cheerful ability to make the most of humanity\'s rubbish and wastefulness. But monitoring suggests a severe decline in the UK House Sparrow population, recently estimated as dropping by 71 per cent between 1977 and 2008 with large falls in both rural and urban populations.',
        seen: 1800,
    },
    {
        name: 'Long-tailed Tit',
        scienceName: 'Aegithalos caudatus',
        alt:'Long-tailed Tit perched on a branch looking to the camera behind',

        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Aegithalos_caudatus_side-on.jpg/440px-Aegithalos_caudatus_side-on.jpg',
        miniSummary: 'The Long-tailed Tit is easily recognisable with its distinctive blush, black and white colouring.',
        bigSummary: 'The Long-tailed Tit is easily recognisable with its distinctive blush, black and white colouring. It also has a tail which is bigger than its body, and a bouncing flight. Sociable and noisy residents, Long-tailed Tits are most usually noticed in small, excitable flocks of about 20 birds. Like most tits, they rove the woods and hedgerows, but are also seen on heaths and commons with suitable bushes. ',
        seen: 1200,
    },
    {
        name: 'Collared Dove',
        scienceName: 'Streptopelia decaocto',
        alt:'Collared Dove perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Eurasian_collared-dove_%28Streptopelia_decaocto%29.jpg/440px-Eurasian_collared-dove_%28Streptopelia_decaocto%29.jpg',
        miniSummary: 'Collared Doves are a pale, pinky-brown-grey colour, with a distinctive black neck collar (as the name suggests).',
        bigSummary: 'Collared Doves are a pale, pinky-brown-grey colour, with a distinctive black neck collar (as the name suggests). They have deep red eyes and reddish feet. Their cooing, which can sometimes seem to go on forever, will be a familiar sound to many of you. Although you\'ll often see them on their own or in pairs, flocks may form where there is a lot of food available.',
        seen: 2500,
    },
    {
        name: 'Magpie',
        scienceName: 'Pica pica',
        alt:'Magpie perched on a branch looking to the right',

        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg/440px-Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg',
        miniSummary: 'With its noisy chattering, black-and-white plumage and long tail, there is nothing else quite like the Magpie.',
        bigSummary: 'With its noisy chattering, black-and-white plumage and long tail, there is nothing else quite like the Magpie in the UK. When seen close-up, its black plumage reveals a purplish-blue iridescent sheen to the wing feathers and a green gloss to the tail. Magpies seem to be jacks of all trades - scavengers, predators and pest-destroyers, their challenging, almost arrogant attitude has won them few friends. ',
        seen: 2000,
    },
    {
        name: 'Chaffinch',
        scienceName: 'Fringilla coelebs',
        alt:'Chaffinch perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Chaffinch_%28Fringilla_coelebs%29.jpg/440px-Chaffinch_%28Fringilla_coelebs%29.jpg',
        miniSummary: 'The Chaffinch is one of the most widespread and common birds in Britain and Ireland. ',
        bigSummary: 'The Chaffinch is one of the most widespread and common birds in Britain and Ireland. Its patterned plumage helps it blend in when feeding on the ground, so it is easiest to see when it flies, as a flash of white on the wings and white outer tail feathers is revealed. It\'s shy when it comes to bird feeders, preferring to hop about under the bird table or under the hedge. ',
        seen: 1500,
    },
    {
        name: 'Wren',
        scienceName: 'Troglodytes troglodytes',
        alt:'Wren perched on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Cistothorus_palustris_Iona.jpg/440px-Cistothorus_palustris_Iona.jpg',
        miniSummary: 'The Wren is a tiny brown bird, although it\'s heavier and not as slim as the even smaller Goldcrest.',
        bigSummary: 'The Wren is a tiny brown bird, although it\'s heavier and not as slim as the even smaller Goldcrest. It\'s almost round in shape with a fine bill, quite long legs and toes, very short round wings and a short, narrow tail, which is sometimes stuck up vertically. For such a small bird, it has a remarkably loud voice. ',
        seen: 800,
    },
    {
        name: 'European Robin',
        scienceName: 'Erithacus rubecula',
        alt:'Robin sitting on a branch looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Erithacus_rubecula_with_cocked_head.jpg/440px-Erithacus_rubecula_with_cocked_head.jpg',
        miniSummary: 'The UK\'s favourite bird. Thanks to its bright red breast it\'s familiar throughout the year.',
        bigSummary: 'The UK\'s favourite bird. Thanks to its bright red breast, it\'s familiar throughout the year and especially at Christmas! Males and females look identical, young birds have no red breast and are spotted with golden brown. Robins sing nearly all year round and despite their cute appearance, they are aggressively territorial and are quick to drive away intruders. They will sing at night next to street lights.',
        seen: 3000,
    },
    {
        name: 'Nuthatch',
        scienceName: 'Sitta europaea',
        alt:'Nuthatch perched on a tree looking to the left',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Sitta_europaea_-Rouge_Cloitre_estate%2C_Sonian_Forest%2C_near_Brussels%2C_Belgium-8.jpg/440px-Sitta_europaea_-Rouge_Cloitre_estate%2C_Sonian_Forest%2C_near_Brussels%2C_Belgium-8.jpg',
        miniSummary: 'The Nuthatch is a plump bird about the size of a Great Tit that resembles a small Woodpecker.',
        bigSummary: 'The Nuthatch is a plump bird about the size of a Great Tit that resembles a small Woodpecker. It\'s blue-grey on top and whitish below, with chestnut on its sides and under its tail. It has a black stripe on its head, a long black pointed bill and short legs. It breeds throughout England and Wales and has recently begun to breed in southern Scotland. ',
        seen: 1200,
    },
];
